In [1]:
import numpy as np

In [57]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [119]:
# Create the new column
new_column = np.array([13, 4, 5])

new_column = np.insert(new_column, new_column.size, 30, axis=0)

print(new_column)


[13  4  5 30]


In [126]:
arr = []
arr.append([[2,2,2],[3,3,3]])

In [123]:
arr = np.append(arr, [[2,2,2],[3,3,3]])

In [128]:
import tensorflow as tf
import numpy as np

# Generate some random data
data = np.random.rand(331, 128)
labels = np.random.randint(0, 2, (331,))

# Define your model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(128,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(data, labels, epochs=10, batch_size=32)

# Evaluate the model
loss, accuracy = model.evaluate(data, labels)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")


Epoch 1/10
11/11 [==============================] - 1s 3ms/step - loss: 0.7014 - accuracy: 0.5166
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6770 - accuracy: 0.5740
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6616 - accuracy: 0.6163
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6465 - accuracy: 0.6375
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6397 - accuracy: 0.6405
Epoch 6/10
11/11 [==============================] - 0s 3ms/step - loss: 0.6414 - accuracy: 0.6375
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6228 - accuracy: 0.6556
Epoch 8/10
11/11 [==============================] - 0s 6ms/step - loss: 0.6061 - accuracy: 0.6858
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 0.6034 - accuracy: 0.6465
Epoch 10/10
11/11 [==============================] - 0s 2ms/step - loss: 0.5571 - accuracy: 0.7583
Test Loss: 0.5571
T

In [131]:
print(data.shape)

(331, 128)


In [129]:
print(labels)

[0 1 1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0
 1 0 0 1 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 0
 1 1 0 0 1 0 0 1 0 1 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0
 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1
 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 1 0 0
 1 1 0 1 0 0 1 1 1 1 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0
 0 1 1 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 1
 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1
 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 0]


In [132]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

# Load and preprocess the dataset
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()
train_images = train_images / 255.0
test_images = test_images / 255.0

# Define the CNN model architecture
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

# Compile the model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Train the model
model.fit(train_images, train_labels, epochs=10, validation_data=(test_images, test_labels))

# Evaluate the model
test_loss, test_accuracy = model.evaluate(test_images, test_labels)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")


170498071/170498071 [==============================] - 18s 0us/step
Epoch 1/10
1563/1563 [==============================] - 41s 26ms/step - loss: 1.5572 - accuracy: 0.4302 - val_loss: 1.2934 - val_accuracy: 0.5396
Epoch 2/10
1563/1563 [==============================] - 39s 25ms/step - loss: 1.1873 - accuracy: 0.5784 - val_loss: 1.0754 - val_accuracy: 0.6207
Epoch 3/10
1563/1563 [==============================] - 40s 25ms/step - loss: 1.0445 - accuracy: 0.6319 - val_loss: 1.0092 - val_accuracy: 0.6450
Epoch 4/10
1563/1563 [==============================] - 40s 25ms/step - loss: 0.9450 - accuracy: 0.6674 - val_loss: 0.9969 - val_accuracy: 0.6545
Epoch 5/10
1563/1563 [==============================] - 40s 26ms/step - loss: 0.8684 - accuracy: 0.6972 - val_loss: 1.0284 - val_accuracy: 0.6397
Epoch 6/10
1563/1563 [==============================] - 47s 30ms/step - loss: 0.8147 - accuracy: 0.7149 - val_loss: 0.8944 - val_accuracy: 0.6913
Epoch 7/10
1563/1563 [==============================] - 

In [111]:
def pad_repeat(spectogram:np.any, width:int):
    counter = 0
    if spectogram.shape[1] > width:
      return spectogram[:, :width]
    else:
        while len(spectogram[0]) < width:
            # Create the new column
            new_column = spectogram[:, counter]
            spectogram = np.insert(spectogram, spectogram[0].size, new_column, axis=1)
            counter += 1  
    return spectogram

In [113]:
arr = pad_repeat(arr,100)
arr.shape[1]

100

In [59]:
np.arange(2)

array([0, 1])

array([ 2,  6, 10])

In [17]:
arr.shape[0]

3